services:
  typescript:
    container_name: typescript
    build: .
    ports:
     - "3000:3000"
    volumes:
      - ./code:/home/
    stdin_open: true
    tty: true

# docker compose up --build --detach
# docker compose exec typescript sh
#   tsc hello.ts
#         --declaration   Generates an additional .d.ts file
#         --watch         Watch for file changes and recompile them on the fly
#   node hello.js
#npx http-server dist -p 3000
